In [2]:
import numpy as np

In [2]:
#list vs numpy

In [3]:
from time import process_time

In [12]:
list1=[i for i in range(100000000)]
s_time=process_time()
list2=[i+5 for i in  range(100000000)]
e_time=process_time()
print(e_time-s_time)

7.09375


In [11]:
np_arr=np.array([i for i in range(100000000)])
s_tim=process_time()
np_arr+=5
e_tim=process_time()
print(e_tim-s_tim)

0.046875


In [13]:
#numpyArrays

In [14]:
l1=[1,4,5,7,8,9]
print(l1)
type(l1)

[1, 4, 5, 7, 8, 9]


list

In [4]:
np_arr1=np.array([1,4,5,7,8,9])
print(np_arr1)
type(np_arr1)

[1 4 5 7 8 9]


numpy.ndarray

In [5]:
np_arr1.shape

(6,)

In [7]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
c=np.array([[1,2,3,0],[3,5,7,9]],dtype=float)          #int,float,str
print(c)

[[1. 2. 3. 0.]
 [3. 5. 7. 9.]]


In [10]:
print(b.shape)
c.shape

(2, 4)


(2, 4)

In [4]:
print(np.__version__)

1.20.3


In [5]:
a=np.array(10)

In [6]:
print(a)

10


In [8]:
b=np.array([10,20,30,40])
print(b)

[10 20 30 40]


In [9]:
b[2]

30

In [12]:
c=np.array([[10,20,30,40],[50,60,70,80]])
print(c)
print(c[0][2])

[[10 20 30 40]
 [50 60 70 80]]
30


In [17]:
d3=[ [[10,20],[30,40],[90,100]] , [[50,60],[70,80],[99,88]] ]
d2=np.asarray(d3,dtype=int)
print(d2)
d2[0][2][0]

[[[ 10  20]
  [ 30  40]
  [ 90 100]]

 [[ 50  60]
  [ 70  80]
  [ 99  88]]]


90

In [18]:
for i in np.nditer(d2):
    print(i)

10
20
30
40
90
100
50
60
70
80
99
88


In [26]:
d2=np.asarray(d3,dtype=float,order='c')
d2


array([[[ 10.,  20.],
        [ 30.,  40.],
        [ 90., 100.]],

       [[ 50.,  60.],
        [ 70.,  80.],
        [ 99.,  88.]]])

In [35]:
buf=b"my Numpy Tutorial is being executed fr"
np.frombuffer(buf,dtype='S2')

array([b'my', b' N', b'um', b'py', b' T', b'ut', b'or', b'ia', b'l ',
       b'is', b' b', b'ei', b'ng', b' e', b'xe', b'cu', b'te', b'd ',
       b'fr'], dtype='|S2')

In [3]:
graph=[[0,10,15,20],[10,0,35,25],[15,35,0,30],[20,25,30,0],[20,25,30,0]]

In [4]:
len(graph[0])

4

In [5]:
len(graph)

5