In [69]:

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [70]:
arr2=np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

## arr3=np.arange(10)
arr3

In [71]:
arr4=np.zeros(5)
arr4

array([0., 0., 0., 0., 0.])

In [72]:
arr5=np.full((2,3),4)
arr5

array([[4, 4, 4],
       [4, 4, 4]])

In [73]:
import numpy as np

In [74]:
arr6=np.eye(5)
print(arr6)
arr7=np.reshape(arr6,(1,25))
print("Array after Reshaping:\n",arr7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Array after Reshaping:
 [[1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  1.]]


In [75]:
np.shape(arr6)

(5, 5)

In [76]:
arr7

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [77]:
arr7.shape

(1, 25)

In [78]:
arr8=np.array([4,5,6,7,8,9],ndmin=6)
arr8

array([[[[[[4, 5, 6, 7, 8, 9]]]]]])

In [79]:
arr8.shape

(1, 1, 1, 1, 1, 6)

In [80]:
arr8.reshape(1,6)
arr8

array([[[[[[4, 5, 6, 7, 8, 9]]]]]])

In [81]:
arr10=np.array([7,8,9,10,11])

In [82]:
arr10

array([ 7,  8,  9, 10, 11])

In [83]:
arr11=np.concatenate((arr,arr10))

In [84]:
arr11

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [85]:
arr13=np.stack((arr,arr10),axis=1)

In [86]:
arr13=np.array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])
print(arr13)
arr15=arr13.flatten(order='C')
print('Array flattening row wise',arr15)
arr16=arr13.flatten(order='F')
print('Array flattening column wise',arr16)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
Array flattening row wise [ 1  7  2  8  3  9  4 10  5 11]
Array flattening column wise [ 1  2  3  4  5  7  8  9 10 11]


In [87]:
arr14=np.hstack((arr,arr10))
arr14

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [88]:
arr14.ndim

1

In [89]:
arr13.ndim

2

In [90]:
arr8.ndim

6

In [91]:
arr8.size

6

In [92]:
arr13.size

10

In [93]:
arr14.size

10

In [94]:
arr15=arr13.flatten(order='C')
arr15

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11])

In [95]:
arr16=arr13.flatten(order='F')
arr16

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [96]:
arr17=arr8.flatten(order='C')
arr17

array([4, 5, 6, 7, 8, 9])

In [97]:
arr13=np.array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])
print('Original','\n',arr13,'\n','Shape',arr13.shape)
arr18=arr13.transpose()
print('Expand along columns:','\n',arr18,'\n','Shape',arr18.shape)


Original 
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] 
 Shape (5, 2)
Expand along columns: 
 [[ 1  2  3  4  5]
 [ 7  8  9 10 11]] 
 Shape (2, 5)


In [98]:
arr18

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [99]:
arr18.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [100]:
arr20=np.pad(arr13,pad_width=((0, 0), (0, 10)),mode='constant', constant_values=0)
arr20

array([[ 1,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 4, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [101]:
arr21=np.pad(arr13,pad_width=((0, 0), (0, 2)),mode='reflect')

In [102]:
arr21

array([[ 1,  7,  1,  7],
       [ 2,  8,  2,  8],
       [ 3,  9,  3,  9],
       [ 4, 10,  4, 10],
       [ 5, 11,  5, 11]])

In [103]:
arr22=np.expand_dims(arr21,axis=2)
arr22

array([[[ 1],
        [ 7],
        [ 1],
        [ 7]],

       [[ 2],
        [ 8],
        [ 2],
        [ 8]],

       [[ 3],
        [ 9],
        [ 3],
        [ 9]],

       [[ 4],
        [10],
        [ 4],
        [10]],

       [[ 5],
        [11],
        [ 5],
        [11]]])

In [104]:
arr22.shape

(5, 4, 1)

In [105]:
arr24=np.squeeze(arr8)
arr24

array([4, 5, 6, 7, 8, 9])

In [106]:
arr8

array([[[[[[4, 5, 6, 7, 8, 9]]]]]])

In [107]:
np.sort(arr21,axis=1)

array([[ 1,  1,  7,  7],
       [ 2,  2,  8,  8],
       [ 3,  3,  9,  9],
       [ 4,  4, 10, 10],
       [ 5,  5, 11, 11]])

In [108]:
arr21

array([[ 1,  7,  1,  7],
       [ 2,  8,  2,  8],
       [ 3,  9,  3,  9],
       [ 4, 10,  4, 10],
       [ 5, 11,  5, 11]])

In [109]:
res=np.zeros_like(arr21)
res

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [110]:
mul=np.array([2,1,3,1])
mul

array([2, 1, 3, 1])

In [111]:
for i in range(arr21.shape[0]):
    res[i,:]=arr21[i,:]*mul
res

array([[ 2,  7,  3,  7],
       [ 4,  8,  6,  8],
       [ 6,  9,  9,  9],
       [ 8, 10, 12, 10],
       [10, 11, 15, 11]])

In [112]:
res1=res+5
res1

array([[ 7, 12,  8, 12],
       [ 9, 13, 11, 13],
       [11, 14, 14, 14],
       [13, 15, 17, 15],
       [15, 16, 20, 16]])

# broadcasting is multiplication of two numpy arrays

In [113]:
res2=res*res1
res2

array([[ 14,  84,  24,  84],
       [ 36, 104,  66, 104],
       [ 66, 126, 126, 126],
       [104, 150, 204, 150],
       [150, 176, 300, 176]])

In [114]:
a = np.array([10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
c=a[:, np.newaxis] + b
d=a+b
print('Adding arrays along the axis:\n',d)
print('Adding arrays along new axis:\n',c)

Adding arrays along the axis:
 [11. 22. 33.]
Adding arrays along new axis:
 [[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [115]:
A = np.array([[11, 59, 54], [50, 55, 67]])
print(A)
b = 4
print('+\n',b)
C = A + b
print('=\n',C)

[[11 59 54]
 [50 55 67]]
+
 4
=
 [[15 63 58]
 [54 59 71]]


In [116]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)
dist


array([17.49285568, 21.58703314, 73.79024326, 56.04462508])

In [117]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a1=np.array(
[
    [
        [0,1,2,3,4],[5,6,7,8,9]
    ],
    [
        [10,11,12,13,14],[15,16,17,18,19]
    ],
    [
        [20,21,22,23,24],[25,26,27,28,29]
    ],
    
]
)
a1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [119]:
a1[0:2,0:1,1:4]

array([[[ 1,  2,  3]],

       [[11, 12, 13]]])

In [120]:
array = np.random.rand(10)
print ("Values of 1D array is:\n", array)

Values of 1D array is:
 [0.91390555 0.41454825 0.84675349 0.90130654 0.36977729 0.18232874
 0.56869656 0.59338919 0.45469616 0.04431514]


In [121]:
arr = np.array([1, 2, 3, 4, 5,6])
print(arr)


[1 2 3 4 5 6]


In [122]:
array_1=np.arange(2,16,2)
print(array_1)

[ 2  4  6  8 10 12 14]


In [123]:
a = np.array([[1,2,3],[4,44,5]])
print('Array :\n',a)
print('Dimensions :',a.ndim)

Array :
 [[ 1  2  3]
 [ 4 44  5]]
Dimensions : 2


In [124]:
a = np.array([[10,21,32],[43,54,65]])
print('Array :\n',a)
print('Shape :',a.shape)

Array :
 [[10 21 32]
 [43 54 65]]
Shape : (2, 3)


In [125]:
a = np.array([[10,21,32],[43,54,65]])
print('Size of array :',a.size)

Size of array : 6


In [126]:
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)
print('Original:\n','Shape',a.shape,'\n',a)
print('Expand along columns:\n','Shape',b.shape,'\n',b)
print('Expand along rows:\n','Shape',c.shape,'\n',c)

Original:
 Shape (3,) 
 [1 2 3]
Expand along columns:
 Shape (1, 3) 
 [[1 2 3]]
Expand along rows:
 Shape (3, 1) 
 [[1]
 [2]
 [3]]


In [127]:
a = np.array([[[1,2,3],
[4,5,6]]])
b = np.squeeze(a, axis=0)
print('Original\n','Shape',a.shape,'\n',a)
print('Squeeze array:\n','Shape',b.shape,'\n',b)

Original
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]
Squeeze array:
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]


In [128]:
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0) 
print ("Along first axis : \n", arr1) 
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1) 
print ("\nAlong negative axis : \n", arr2)
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None) 
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along negative axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [129]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [130]:
arr = np.array([[10, 20, 30, 41, 52], [1,2,3,4,5]])
print(arr[1:, 1:4])

[[2 3 4]]


In [131]:

a3=np.array([ [[11,12,13], [14,15,16], [17,18,19]],
 [[21,22,23], [24,25,26,], [27,28,29]]])
print(a3[0:,0,0])

[11 21]


In [132]:
arr = np.array([1, 21, 32, 43, 59, 54, 7])
print(arr[-3:-1])

[59 54]


In [133]:
arr = np.array([1,2002,7012,685 ,27, 3, 54, 59, 6, 7])
print(arr[1:9:2])

[2002  685    3   59]


In [134]:
x = np.array([1,2, 3, 4])
y = np.array([3, 4, 5,6])
np.stack((x, y))

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [135]:
np.stack((x, y), axis=-1)

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [136]:
x=np.array([[1,2,3], [4,5,6]])
y=np.array([[7,8,9], [10,11,12]])
z=np.array([[13,14,15], [16,17,18]])
np.stack((x,y,z),axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [137]:
arr = np.array([54, 57, 12]) 
arr1 = np.array([59, 95, 143])
con = np.concatenate((arr, arr1)) 
print(con)

[ 54  57  12  59  95 143]


In [155]:
arr55=np.array([
   [[33,11,44,22],
    [77,88,99,55]],
   [[76,87,98,54],
    [32,10,43,21]]
                  ])

In [156]:
arr55

array([[[33, 11, 44, 22],
        [77, 88, 99, 55]],

       [[76, 87, 98, 54],
        [32, 10, 43, 21]]])

In [157]:
arr56=np.sort(arr55,axis=0)
arr57=np.sort(arr55,axis=1)
arr58=np.sort(arr55,axis=-1)

In [158]:
print(arr55)

[[[33 11 44 22]
  [77 88 99 55]]

 [[76 87 98 54]
  [32 10 43 21]]]


In [159]:
print(arr56)

[[[33 11 44 22]
  [32 10 43 21]]

 [[76 87 98 54]
  [77 88 99 55]]]


In [162]:
print(arr57)

[[[33 11 44 22]
  [77 88 99 55]]

 [[32 10 43 21]
  [76 87 98 54]]]


In [163]:
print(arr58)

[[[11 22 33 44]
  [55 77 88 99]]

 [[54 76 87 98]
  [10 21 32 43]]]
